version: '3.7'

services:
  cassandra-db:
    network_mode: bridge
    image: cassandra
    ports:
      - "9042:9042"
  application:
    network_mode: bridge
    container_name: messages-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure